# Generated by Django 3.1.4 on 2021-01-25 20:02

import datetime
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    replaces = [('jobs', '0001_initial'), ('jobs', '0002_auto_20201210_1311'), ('jobs', '0003_emap2secjob_gnorm'), ('jobs', '0004_auto_20201210_2038'), ('jobs', '0005_auto_20201210_2044'), ('jobs', '0006_auto_20201210_2049'), ('jobs', '0007_auto_20201210_2102'), ('jobs', '0008_auto_20201210_2103'), ('jobs', '0009_auto_20201210_2117'), ('jobs', '0010_auto_20201210_2213'), ('jobs', '0011_auto_20201210_2253'), ('jobs', '0012_auto_20201210_2313'), ('jobs', '0013_auto_20201210_2346'), ('jobs', '0014_auto_20201211_0028'), ('jobs', '0015_auto_20201211_0219'), ('jobs', '0016_auto_20201211_0220'), ('jobs', '0017_auto_20201222_2135'), ('jobs', '0018_auto_20201222_2143'), ('jobs', '0019_auto_20201222_2145'), ('jobs', '0020_auto_20201224_1608'), ('jobs', '0021_auto_20210125_1450'), ('jobs', '0022_auto_20210125_1458'), ('jobs', '0023_auto_20210125_1458')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emap2SecJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mrc_file', models.FileField(upload_to=None)),
                ('contour', models.FloatField(default=0.0)),
                ('sstep', models.IntegerField(default=2)),
                ('vw', models.IntegerField(default=5)),
                ('gnorm', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterModelTable(
            name='emap2secjob',
            table='Emap2Sec',
        ),
        migrations.AlterModelOptions(
            name='emap2secjob',
            options={'verbose_name': 'Emap2Sec Job', 'verbose_name_plural': 'Emap2Sec Jobs'},
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='contour',
            field=models.FloatField(default=0.0, verbose_name='Contour'),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='gnorm',
            field=models.BooleanField(default=False, verbose_name='Normalize Density Values'),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='mrc_file',
            field=models.FileField(upload_to=None, verbose_name='MRC File'),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='sstep',
            field=models.IntegerField(default=2, verbose_name='Stride Step'),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='vw',
            field=models.IntegerField(default=5, verbose_name='Sliding Cube Size'),
        ),
        migrations.AlterModelTable(
            name='emap2secjob',
            table='emap2sec',
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='mrc_file',
            field=models.FileField(upload_to='C:\\Users\\ljf\\git\\emsuite_web\\media', verbose_name='MRC File'),
        ),
        migrations.AddField(
            model_name='emap2secjob',
            name='mrc_filename',
            field=models.CharField(default='', max_length=260, verbose_name='MRC Filename'),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='mrc_file',
            field=models.FileField(null=True, upload_to='C:\\Users\\ljf\\git\\emsuite_web\\media', verbose_name='MRC File'),
        ),
        migrations.RemoveField(
            model_name='emap2secjob',
            name='gnorm',
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='sstep',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Stride Step'),
        ),
        migrations.AddField(
            model_name='emap2secjob',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Queued'), (1, 'Running'), (2, 'Completed'), (3, 'Failed')], default=0),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='vw',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Sliding Cube Size'),
        ),
        migrations.AddField(
            model_name='emap2secjob',
            name='name',
            field=models.CharField(default='', max_length=300, verbose_name='Job Name'),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='contour',
            field=models.FloatField(default=0.0, verbose_name='Contour Level'),
        ),
        migrations.AddField(
            model_name='emap2secjob',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Comment'),
        ),
        migrations.RemoveField(
            model_name='emap2secjob',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='emap2secjob',
            name='time_sub',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submission Time'),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='mrc_file',
            field=models.FileField(null=True, upload_to='emap2sec', verbose_name='MRC File'),
        ),
        migrations.AddField(
            model_name='emap2secjob',
            name='norm',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Global'), (2, 'Local')], default=1, verbose_name='Density Normalization'),
        ),
        migrations.RemoveField(
            model_name='emap2secjob',
            name='id',
        ),
        migrations.AddField(
            model_name='emap2secjob',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.CreateModel(
            name='Emap2SecPlusJob',
            fields=[
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Queued'), (1, 'Running'), (2, 'Completed'), (3, 'Failed')], default=0)),
                ('mrc_file', models.FileField(null=True, upload_to='emap2secplus', verbose_name='MRC File')),
                ('mrc_filename', models.CharField(default='', max_length=260, verbose_name='MRC Filename')),
                ('time_sub', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submission Time')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
            ],
            options={
                'verbose_name': 'Emap2Sec+ Job',
                'verbose_name_plural': 'Emap2Sec+ Jobs',
                'db_table': 'emap2sec_plus',
            },
        ),
        migrations.CreateModel(
            name='MainmastJob',
            fields=[
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Queued'), (1, 'Running'), (2, 'Completed'), (3, 'Failed')], default=0)),
                ('mrc_file', models.FileField(null=True, upload_to='mainmast', verbose_name='MRC File')),
                ('mrc_filename', models.CharField(default='', max_length=260, verbose_name='MRC Filename')),
                ('time_sub', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submission Time')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
            ],
            options={
                'verbose_name': 'MAINMAST Job',
                'verbose_name_plural': 'MAINMAST Jobs',
                'db_table': 'mainmast',
            },
        ),
        migrations.CreateModel(
            name='MainmastSegJob',
            fields=[
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Queued'), (1, 'Running'), (2, 'Completed'), (3, 'Failed')], default=0)),
                ('mrc_file', models.FileField(null=True, upload_to='mainmastseg', verbose_name='MRC File')),
                ('mrc_filename', models.CharField(default='', max_length=260, verbose_name='MRC Filename')),
                ('time_sub', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submission Time')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
            ],
            options={
                'verbose_name': 'MAINMASTseg Job',
                'verbose_name_plural': 'MAINMASTseg Jobs',
                'db_table': 'mainmast_seg',
            },
        ),
    ]
