# Generated by Django 3.1.2 on 2020-12-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emap2SecJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrc_file', models.FileField(upload_to=None)),
                ('contour', models.FloatField()),
            ],
        ),
    ]
