# Generated by Django 3.1.6 on 2021-03-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emap2secjob',
            name='mrc_file',
        ),
        migrations.RemoveField(
            model_name='emap2secjob',
            name='mrc_filename',
        ),
        migrations.RemoveField(
            model_name='emap2secplusjob',
            name='mrc_file',
        ),
        migrations.RemoveField(
            model_name='emap2secplusjob',
            name='mrc_filename',
        ),
        migrations.RemoveField(
            model_name='mainmastjob',
            name='mrc_file',
        ),
        migrations.RemoveField(
            model_name='mainmastjob',
            name='mrc_filename',
        ),
        migrations.RemoveField(
            model_name='mainmastsegjob',
            name='mrc_file',
        ),
        migrations.RemoveField(
            model_name='mainmastsegjob',
            name='mrc_filename',
        ),
        migrations.AddField(
            model_name='emap2secjob',
            name='map_file',
            field=models.FileField(null=True, upload_to='emap2sec', verbose_name='Map File'),
        ),
        migrations.AddField(
            model_name='emap2secjob',
            name='map_filename',
            field=models.CharField(default='', max_length=260, verbose_name='Map Filename'),
        ),
        migrations.AddField(
            model_name='emap2secplusjob',
            name='map_file',
            field=models.FileField(null=True, upload_to='emap2secplus', verbose_name='Map File'),
        ),
        migrations.AddField(
            model_name='emap2secplusjob',
            name='map_filename',
            field=models.CharField(default='', max_length=260, verbose_name='Map Filename'),
        ),
        migrations.AddField(
            model_name='mainmastjob',
            name='Const',
            field=models.FloatField(default=1.01, verbose_name='Tree Length Constraint'),
        ),
        migrations.AddField(
            model_name='mainmastjob',
            name='Dkeep',
            field=models.FloatField(default=0.5, verbose_name='Edge Length Threshold'),
        ),
        migrations.AddField(
            model_name='mainmastjob',
            name='Nnb',
            field=models.PositiveIntegerField(default=30, verbose_name='Candidates per Iteration'),
        ),
        migrations.AddField(
            model_name='mainmastjob',
            name='Nround',
            field=models.PositiveIntegerField(default=5000, verbose_name='Number of Iterations'),
        ),
        migrations.AddField(
            model_name='mainmastjob',
            name='Ntb',
            field=models.PositiveIntegerField(default=100, verbose_name='Tabu List Size'),
        ),
        migrations.AddField(
            model_name='mainmastjob',
            name='Rlocal',
            field=models.FloatField(default=10.0, verbose_name='Local MST Radius'),
        ),
        migrations.AddField(
            model_name='mainmastjob',
            name='allow',
            field=models.FloatField(default=10.0, verbose_name='Maximum Shift Distance'),
        ),
        migrations.AddField(
            model_name='mainmastjob',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='mainmastjob',
            name='filter',
            field=models.FloatField(default=0.1, verbose_name='Seed Point Density Threshold'),
        ),
        migrations.AddField(
            model_name='mainmastjob',
            name='gw',
            field=models.FloatField(default=2.0, verbose_name='Gaussian Kernel Bandwidth'),
        ),
        migrations.AddField(
            model_name='mainmastjob',
            name='map_file',
            field=models.FileField(null=True, upload_to='mainmast', verbose_name='Map File'),
        ),
        migrations.AddField(
            model_name='mainmastjob',
            name='map_filename',
            field=models.CharField(default='', max_length=260, verbose_name='Map Filename'),
        ),
        migrations.AddField(
            model_name='mainmastjob',
            name='merge',
            field=models.FloatField(default=0.5, verbose_name='Merge Threshold'),
        ),
        migrations.AddField(
            model_name='mainmastjob',
            name='name',
            field=models.CharField(default='', max_length=300, verbose_name='Job Name'),
        ),
        migrations.AddField(
            model_name='mainmastjob',
            name='t',
            field=models.FloatField(default=0.0, verbose_name='Grid Point Density Threshold'),
        ),
        migrations.AddField(
            model_name='mainmastsegjob',
            name='map_file',
            field=models.FileField(null=True, upload_to='mainmastseg', verbose_name='Map File'),
        ),
        migrations.AddField(
            model_name='mainmastsegjob',
            name='map_filename',
            field=models.CharField(default='', max_length=260, verbose_name='Map Filename'),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='norm',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Global'), (1, 'Local')], default=1, verbose_name='Density Normalization'),
        ),
    ]
