# Generated by Django 3.1.2 on 2020-12-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emap2secjob',
            name='sstep',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emap2secjob',
            name='vw',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
