# Generated by Django 3.1.6 on 2021-09-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210318_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='emap2secjob',
            name='solved_structure',
            field=models.FileField(null=True, upload_to='emap2sec/solved', verbose_name='Solved Crystal Structure'),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='map_file',
            field=models.FileField(null=True, upload_to='emap2sec/input', verbose_name='Map File'),
        ),
    ]
