# Generated by Django 3.1.2 on 2020-12-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20201210_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='emap2secjob',
            name='gnorm',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
