# Generated by Django 3.1.2 on 2020-12-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_emap2secjob_gnorm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emap2secjob',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
