# Generated by Django 3.1.6 on 2022-02-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210906_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='emap2secplusjob',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='emap2secplusjob',
            name='contour',
            field=models.FloatField(default=0.0, verbose_name='Contour Level'),
        ),
        migrations.AddField(
            model_name='emap2secplusjob',
            name='name',
            field=models.CharField(default='', max_length=300, verbose_name='Job Name'),
        ),
        migrations.AddField(
            model_name='emap2secplusjob',
            name='resize',
            field=models.BooleanField(default=True, verbose_name='Resize'),
        ),
        migrations.AddField(
            model_name='emap2secplusjob',
            name='type',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Map Type'),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='solved_structure',
            field=models.FileField(blank=True, null=True, upload_to='emap2sec/solved', verbose_name='Solved Crystal Structure'),
        ),
    ]
