# Generated by Django 3.1.6 on 2022-02-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20220224_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emap2secplusjob',
            name='map_file',
            field=models.FileField(null=True, upload_to='emap2secplus/input', verbose_name='Map File'),
        ),
    ]
