# Generated by Django 3.1.2 on 2020-12-11 01:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20201210_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emap2secjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
