# Generated by Django 3.1.2 on 2020-12-11 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20201210_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='emap2secjob',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='contour',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='gnorm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='sstep',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='vw',
            field=models.IntegerField(default=5),
        ),
    ]
