# Generated by Django 3.1.6 on 2022-02-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20220225_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emap2secplusjob',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Simulated (6 Å)'), (1, 'Simulated (6-10 Å)'), (2, 'Simulated (10 Å)'), (3, 'Experimental')], default=1, verbose_name='Map Type'),
        ),
    ]
