# Generated by Django 3.1.6 on 2022-03-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20220225_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmastjob',
            name='Ab',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Simulated (6 Å)'), (1, 'Simulated (6-10 Å)')], default=0, verbose_name='Average Bond Length'),
        ),
        migrations.AddField(
            model_name='mainmastjob',
            name='Wb',
            field=models.FloatField(default=0.9, verbose_name='Bond Score Weight'),
        ),
        migrations.AddField(
            model_name='mainmastjob',
            name='fw',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Simulated (6 Å)'), (1, 'Simulated (6-10 Å)')], default=0, verbose_name='Filter Width'),
        ),
        migrations.AlterField(
            model_name='emap2secplusjob',
            name='map_file',
            field=models.FileField(null=True, upload_to='emap2secplus/input', verbose_name='Map File'),
        ),
        migrations.AlterField(
            model_name='mainmastjob',
            name='Dkeep',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Simulated (6 Å)'), (1, 'Simulated (6-10 Å)')], default=0, verbose_name='Edge Length Threshold'),
        ),
        migrations.AlterField(
            model_name='mainmastjob',
            name='Rlocal',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Simulated (6 Å)'), (1, 'Simulated (6-10 Å)')], default=0, verbose_name='Local MST Radius'),
        ),
        migrations.AlterField(
            model_name='mainmastjob',
            name='filter',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Simulated (6 Å)'), (1, 'Simulated (6-10 Å)')], default=0, verbose_name='Seed Point Density Threshold'),
        ),
        migrations.AlterField(
            model_name='mainmastjob',
            name='map_file',
            field=models.FileField(null=True, upload_to='mainmast/input', verbose_name='Map File'),
        ),
    ]
