# Generated by Django 3.1.2 on 2020-12-11 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20201210_2102'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emap2secjob',
            table='Emap2Sec',
        ),
    ]
