# Generated by Django 3.1.2 on 2020-12-11 02:17

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20201210_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emap2secjob',
            options={'verbose_name': 'Emap2Sec Job', 'verbose_name_plural': 'Emap2Sec Jobs'},
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='contour',
            field=models.FloatField(default=0.0, verbose_name='Contour'),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='gnorm',
            field=models.BooleanField(default=False, verbose_name='Normalize Density Values'),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='mrc_file',
            field=models.FileField(upload_to=None, verbose_name='MRC File'),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='sstep',
            field=models.IntegerField(default=2, verbose_name='Stride Step'),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='vw',
            field=models.IntegerField(default=5, verbose_name='Sliding Cube Size'),
        ),
        migrations.AlterModelTable(
            name='emap2secjob',
            table='emap2sec',
        ),
    ]
