# Generated by Django 3.1.6 on 2022-03-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20220331_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmastjob',
            name='Ab',
            field=models.PositiveSmallIntegerField(choices=[(0, '3.5'), (1, '3.2, 3.4, 3.6, 3.8 '), (2, '3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8')], default=0, verbose_name='Average Bond Length'),
        ),
        migrations.AlterField(
            model_name='mainmastjob',
            name='Dkeep',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.5'), (1, '0.5, 1.0, 1.5')], default=0, verbose_name='Edge Length Threshold'),
        ),
        migrations.AlterField(
            model_name='mainmastjob',
            name='Rlocal',
            field=models.PositiveSmallIntegerField(choices=[(0, '10.0'), (1, '5.0, 7.5, 10.0')], default=0, verbose_name='Local MST Radius'),
        ),
        migrations.AlterField(
            model_name='mainmastjob',
            name='filter',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.1'), (1, '0.0, 0.1, 0.2, 0.3')], default=0, verbose_name='Seed Point Density Threshold'),
        ),
        migrations.AlterField(
            model_name='mainmastjob',
            name='fw',
            field=models.PositiveSmallIntegerField(choices=[(0, '1.0'), (1, '0.9, 1.1, 1.3'), (2, '0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4')], default=0, verbose_name='Filter Width'),
        ),
    ]
