# Generated by Django 3.1.2 on 2020-12-11 03:13

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20201210_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emap2SecPlusJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Timestamp')),
                ('status', models.CharField(choices=[('Q', 'Queued'), ('R', 'Running'), ('C', 'Completed'), ('F', 'Failed')], default='Q', max_length=1)),
            ],
            options={
                'verbose_name': 'Emap2Sec+ Job',
                'verbose_name_plural': 'Emap2Sec+ Jobs',
                'db_table': 'emap2sec_plus',
            },
        ),
        migrations.CreateModel(
            name='MainmastJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Timestamp')),
                ('status', models.CharField(choices=[('Q', 'Queued'), ('R', 'Running'), ('C', 'Completed'), ('F', 'Failed')], default='Q', max_length=1)),
            ],
            options={
                'verbose_name': 'MAINMAST Job',
                'verbose_name_plural': 'MAINMAST Jobs',
                'db_table': 'mainmast',
            },
        ),
        migrations.CreateModel(
            name='MainmastSegJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Timestamp')),
                ('status', models.CharField(choices=[('Q', 'Queued'), ('R', 'Running'), ('C', 'Completed'), ('F', 'Failed')], default='Q', max_length=1)),
            ],
            options={
                'verbose_name': 'MAINMASTseg Job',
                'verbose_name_plural': 'MAINMASTseg Jobs',
                'db_table': 'mainmast_seg',
            },
        ),
        migrations.AddField(
            model_name='emap2secjob',
            name='status',
            field=models.CharField(choices=[('Q', 'Queued'), ('R', 'Running'), ('C', 'Completed'), ('F', 'Failed')], default='Q', max_length=1),
        ),
    ]
