# Generated by Django 3.1.2 on 2020-12-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20201210_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='emap2secjob',
            name='mrc_filename',
            field=models.CharField(default='', max_length=260, verbose_name='MRC Filename'),
        ),
        migrations.AddField(
            model_name='emap2secplusjob',
            name='mrc_file',
            field=models.FileField(null=True, upload_to='C:\\Users\\ljf\\git\\emsuite_web\\media', verbose_name='MRC File'),
        ),
        migrations.AddField(
            model_name='emap2secplusjob',
            name='mrc_filename',
            field=models.CharField(default='', max_length=260, verbose_name='MRC Filename'),
        ),
        migrations.AddField(
            model_name='mainmastjob',
            name='mrc_file',
            field=models.FileField(null=True, upload_to='C:\\Users\\ljf\\git\\emsuite_web\\media', verbose_name='MRC File'),
        ),
        migrations.AddField(
            model_name='mainmastjob',
            name='mrc_filename',
            field=models.CharField(default='', max_length=260, verbose_name='MRC Filename'),
        ),
        migrations.AddField(
            model_name='mainmastsegjob',
            name='mrc_file',
            field=models.FileField(null=True, upload_to='C:\\Users\\ljf\\git\\emsuite_web\\media', verbose_name='MRC File'),
        ),
        migrations.AddField(
            model_name='mainmastsegjob',
            name='mrc_filename',
            field=models.CharField(default='', max_length=260, verbose_name='MRC Filename'),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='mrc_file',
            field=models.FileField(null=True, upload_to='C:\\Users\\ljf\\git\\emsuite_web\\media', verbose_name='MRC File'),
        ),
    ]
