# Generated by Django 3.1.2 on 2020-12-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20201210_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emap2secjob',
            name='gnorm',
        ),
        migrations.AddField(
            model_name='emap2secjob',
            name='norm',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Global'), (2, 'Local')], default=0, verbose_name='Density Normalization'),
        ),
    ]
