# Generated by Django 3.1.2 on 2020-12-11 07:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20201211_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emap2secjob',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 7, 19, 44, 763527, tzinfo=utc), verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='emap2secplusjob',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 7, 19, 44, 763527, tzinfo=utc), verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='mainmastjob',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 7, 19, 44, 763527, tzinfo=utc), verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='mainmastsegjob',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 7, 19, 44, 763527, tzinfo=utc), verbose_name='Timestamp'),
        ),
    ]
