# Generated by Django 3.1.4 on 2020-12-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_auto_20201211_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='emap2secjob',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='emap2secjob',
            name='name',
            field=models.CharField(default='', max_length=300, verbose_name='Job Name'),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='contour',
            field=models.FloatField(default=0.0, verbose_name='Contour Level'),
        ),
    ]
