# Generated by Django 3.1.4 on 2020-12-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_auto_20201222_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emap2secjob',
            name='comment',
            field=models.TextField(default='', verbose_name='Comment'),
        ),
    ]
