# Generated by Django 3.1.4 on 2021-01-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_auto_20201224_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emap2secjob',
            name='mrc_file',
            field=models.FileField(null=True, upload_to='emap2sec', verbose_name='MRC File'),
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='norm',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Global'), (2, 'Local')], default=1, verbose_name='Density Normalization'),
        ),
        migrations.AlterField(
            model_name='emap2secplusjob',
            name='mrc_file',
            field=models.FileField(null=True, upload_to='emap2secplus', verbose_name='MRC File'),
        ),
        migrations.AlterField(
            model_name='mainmastjob',
            name='mrc_file',
            field=models.FileField(null=True, upload_to='mainmast', verbose_name='MRC File'),
        ),
        migrations.AlterField(
            model_name='mainmastsegjob',
            name='mrc_file',
            field=models.FileField(null=True, upload_to='mainmastseg', verbose_name='MRC File'),
        ),
    ]
