# Generated by Django 3.1.4 on 2021-01-25 19:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_auto_20210125_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emap2secjob',
            name='id',
        ),
        migrations.RemoveField(
            model_name='emap2secplusjob',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mainmastjob',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mainmastsegjob',
            name='id',
        ),
        migrations.AlterField(
            model_name='emap2secjob',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='emap2secplusjob',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='mainmastjob',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='mainmastsegjob',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
